-- File table
CREATE TABLE file (
  id SERIAL PRIMARY KEY,
  file_uri VARCHAR,
  file_name VARCHAR,
  environment_id INTEGER,
  status VARCHAR NOT NULL DEFAULT 'PENDING',
  error_message VARCHAR,
  uploader_id INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);